# Generated by Django 4.2.10 on 2024-02-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gymClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(blank=True)),
                ('endTime', models.DateTimeField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='gymClient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('homePhone', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('photoURL', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gymCheckin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkinTime', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField(blank=True, default=0)),
                ('long', models.FloatField(blank=True, default=0)),
                ('distance', models.FloatField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGymCheckin.gymclient')),
                ('gymClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyGymCheckin.gymclass')),
            ],
        ),
    ]
