# Generated by Django 4.2.10 on 2024-02-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyGymCheckin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymcheckin',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
